import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";
export const admins=sqliteTable("admins",{id:integer("id").primaryKey({autoIncrement:true}),username:text("username").notNull().unique(),passwordHash:text("password_hash").notNull(),salt:text("salt").notNull(),createdAt:integer("created_at").notNull()});
export const sessions=sqliteTable("sessions",{id:text("id").primaryKey(),adminId:integer("admin_id").notNull().references(()=>admins.id,{onDelete:"cascade"}),tokenHash:text("token_hash").notNull().unique(),expiresAt:integer("expires_at").notNull(),createdAt:integer("created_at").notNull()});
export const categories=sqliteTable("categories",{id:integer("id").primaryKey({autoIncrement:true}),name:text("name").notNull(),slug:text("slug").notNull().unique(),icon:text("icon").notNull().default("🧸"),imageUrl:text("image_url"),parentId:integer("parent_id"),sortOrder:integer("sort_order").notNull().default(0),active:integer("active",{mode:"boolean"}).notNull().default(true)});
export const products=sqliteTable("products",{id:integer("id").primaryKey({autoIncrement:true}),name:text("name").notNull(),slug:text("slug").notNull().unique(),sku:text("sku").notNull().unique(),categoryId:integer("category_id").references(()=>categories.id),shortDescription:text("short_description"),description:text("description"),notes:text("notes"),price:integer("price").notNull(),cost:integer("cost").notNull().default(0),oldPrice:integer("old_price"),gender:text("gender"),active:integer("active",{mode:"boolean"}).notNull().default(true),featured:integer("featured",{mode:"boolean"}).notNull().default(false),newArrival:integer("new_arrival",{mode:"boolean"}).notNull().default(false),offer:integer("offer",{mode:"boolean"}).notNull().default(false),bestSeller:integer("best_seller",{mode:"boolean"}).notNull().default(false),attributes:text("attributes",{mode:"json"}).$type<Record<string,string>>(),createdAt:integer("created_at").notNull(),updatedAt:integer("updated_at").notNull()});
export const variants=sqliteTable("variants",{id:integer("id").primaryKey({autoIncrement:true}),productId:integer("product_id").notNull().references(()=>products.id,{onDelete:"cascade"}),colorName:text("color_name"),colorHex:text("color_hex"),size:text("size"),age:text("age"),stock:integer("stock").notNull().default(0),priceOverride:integer("price_override"),active:integer("active",{mode:"boolean"}).notNull().default(true),sortOrder:integer("sort_order").notNull().default(0)});
export const variantImages=sqliteTable("variant_images",{id:integer("id").primaryKey({autoIncrement:true}),variantId:integer("variant_id").notNull().references(()=>variants.id,{onDelete:"cascade"}),imageUrl:text("image_url").notNull(),objectKey:text("object_key"),alt:text("alt"),sortOrder:integer("sort_order").notNull().default(0),isMain:integer("is_main",{mode:"boolean"}).notNull().default(false)});
export const settings=sqliteTable("settings",{key:text("key").primaryKey(),value:text("value").notNull(),updatedAt:integer("updated_at").notNull()});
export const banners=sqliteTable("banners",{id:integer("id").primaryKey({autoIncrement:true}),title:text("title").notNull(),subtitle:text("subtitle"),imageUrl:text("image_url"),buttonText:text("button_text"),buttonLink:text("button_link"),style:text("style",{mode:"json"}).$type<Record<string,string|number|boolean>>(),sortOrder:integer("sort_order").notNull().default(0),active:integer("active",{mode:"boolean"}).notNull().default(true)});
export const orders=sqliteTable("orders",{id:integer("id").primaryKey({autoIncrement:true}),orderNumber:text("order_number").notNull().unique(),customerName:text("customer_name").notNull(),phone:text("phone").notNull(),governorate:text("governorate"),address:text("address").notNull(),landmark:text("landmark"),notes:text("notes"),status:text("status").notNull().default("pending"),inventoryApplied:integer("inventory_applied",{mode:"boolean"}).notNull().default(false),total:integer("total").notNull(),deliveryFee:integer("delivery_fee").notNull().default(0),totalCost:integer("total_cost").notNull().default(0),createdAt:integer("created_at").notNull(),approvedAt:integer("approved_at"),shippingAt:integer("shipping_at"),deliveredAt:integer("delivered_at")});
export const orderItems=sqliteTable("order_items",{id:integer("id").primaryKey({autoIncrement:true}),orderId:integer("order_id").notNull().references(()=>orders.id,{onDelete:"cascade"}),productId:integer("product_id"),variantId:integer("variant_id"),productName:text("product_name").notNull(),productCode:text("product_code"),colorName:text("color_name"),size:text("size"),age:text("age"),quantity:integer("quantity").notNull(),unitPrice:integer("unit_price").notNull(),unitCost:integer("unit_cost").notNull().default(0),imageUrl:text("image_url"),status:text("status").notNull().default("pending"),inventoryApplied:integer("inventory_applied",{mode:"boolean"}).notNull().default(false),approvedAt:integer("approved_at")});
export const seasonalEffects=sqliteTable("seasonal_effects",{
  id:integer("id").primaryKey({autoIncrement:true}),name:text("name").notNull(),preset:text("preset").notNull().default("winter"),active:integer("active",{mode:"boolean"}).notNull().default(false),startDate:text("start_date"),endDate:text("end_date"),speed:text("speed").notNull().default("normal"),density:integer("density").notNull().default(25),opacity:integer("opacity").notNull().default(35),elementSize:integer("element_size").notNull().default(24),motion:text("motion").notNull().default("fall"),desktopEnabled:integer("desktop_enabled",{mode:"boolean"}).notNull().default(true),mobileEnabled:integer("mobile_enabled",{mode:"boolean"}).notNull().default(true),pages:text("pages").notNull().default("home,products"),customSymbols:text("custom_symbols"),barEnabled:integer("bar_enabled",{mode:"boolean"}).notNull().default(false),barText:text("bar_text"),barTextColor:text("bar_text_color").notNull().default("#ffffff"),barBackground:text("bar_background").notNull().default("#8b5e83"),barLink:text("bar_link"),sortOrder:integer("sort_order").notNull().default(0),createdAt:integer("created_at").notNull(),updatedAt:integer("updated_at").notNull()
});
export const paymentMethods=sqliteTable("payment_methods",{
  id:integer("id").primaryKey({autoIncrement:true}),name:text("name").notNull(),logoUrl:text("logo_url"),active:integer("active",{mode:"boolean"}).notNull().default(true),sortOrder:integer("sort_order").notNull().default(0),actionType:text("action_type").notNull().default("whatsapp"),whatsappMessage:text("whatsapp_message"),directUrl:text("direct_url"),createdAt:integer("created_at").notNull(),updatedAt:integer("updated_at").notNull()
});
