"use client";
import {useEffect,useState} from "react";
import {ArrowRight,Plus,Save,Trash2} from "lucide-react";
type Cat={id:number;name:string;icon:string;parentId?:number|null;active:boolean;sortOrder:number};const icons=["👕","👶","🎀","🛏️","🍼","🛒","🧷","🧸","👧","👦","🤍","🧢","👟","🛁","🎁"];
export default function Categories(){const [cats,setCats]=useState<Cat[]>([]),[name,setName]=useState(""),[icon,setIcon]=useState("🧸"),[parentId,setParentId]=useState(""),[notice,setNotice]=useState("");
 async function load(){const r=await fetch('/api/categories?admin=1');if(r.status===401){location.href='/admin';return}setCats((await r.json()).categories||[])}useEffect(()=>{load()},[]);
 async function add(e:React.FormEvent){e.preventDefault();const r=await fetch('/api/categories',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name,icon,parentId:parentId?+parentId:null})});if(r.ok){setName('');setParentId('');setNotice('تمت إضافة القسم');load()}}
 async function presets(){await fetch('/api/categories',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'installPresets'})});setNotice('تمت إضافة الأقسام والفرعيات المقترحة، وتكدر تعدل أو تحذف أي واحد');load()}
 async function save(c:Cat){const r=await fetch(`/api/categories/${c.id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(c)});if(r.ok)setNotice('تم حفظ التعديل')}
 async function remove(id:number){if(!confirm('هل أنت متأكد من حذف القسم؟'))return;const r=await fetch(`/api/categories/${id}`,{method:'DELETE'});if(r.ok){setNotice('تم حذف القسم');load()}else setNotice((await r.json()).error||'تعذر الحذف')}
 return <main dir="rtl" className="min-h-screen bg-[#fff9fb] p-4 md:p-8"><div className="mx-auto max-w-6xl"><a href="/admin" className="inline-flex gap-2"><ArrowRight/> رجوع للوحة</a><div className="mt-5 flex flex-wrap justify-between gap-3"><div><h1 className="text-3xl font-black">إدارة الأقسام</h1><p>القسم الرئيسي يحتوي أقساماً فرعية، وكل اسم وأيقونة قابلان للتعديل والحذف.</p></div><button onClick={presets} className="btn-soft">إضافة المقترحات الكاملة</button></div>{notice&&<p className="my-4 rounded-xl bg-[#dff0f8] p-3">{notice}</p>}<form onSubmit={add} className="my-6 grid gap-3 rounded-3xl bg-white p-5 md:grid-cols-[1fr_120px_1fr_auto]"><input required value={name} onChange={e=>setName(e.target.value)} placeholder="اسم القسم" className="input"/><IconSelect value={icon} onChange={setIcon}/><select value={parentId} onChange={e=>setParentId(e.target.value)} className="input"><option value="">قسم رئيسي</option>{cats.filter(c=>!c.parentId).map(c=><option key={c.id} value={c.id}>{c.icon} {c.name}</option>)}</select><button className="btn-soft"><Plus/> إضافة</button></form><div className="space-y-3">{cats.map((c,i)=><div key={c.id} className="grid items-center gap-3 rounded-2xl bg-white p-4 md:grid-cols-[45px_100px_1fr_1fr_90px_auto]"><b>{i+1}</b><IconSelect value={c.icon||'🧸'} onChange={v=>setCats(a=>a.map(x=>x.id===c.id?{...x,icon:v}:x))}/><input value={c.name} onChange={e=>setCats(a=>a.map(x=>x.id===c.id?{...x,name:e.target.value}:x))} className="input"/><select value={c.parentId||''} onChange={e=>setCats(a=>a.map(x=>x.id===c.id?{...x,parentId:e.target.value?+e.target.value:null}:x))} className="input"><option value="">رئيسي</option>{cats.filter(x=>!x.parentId&&x.id!==c.id).map(x=><option key={x.id} value={x.id}>{x.icon} {x.name}</option>)}</select><label><input type="checkbox" checked={c.active} onChange={e=>setCats(a=>a.map(x=>x.id===c.id?{...x,active:e.target.checked}:x))}/> ظاهر</label><div className="flex gap-2"><button onClick={()=>save(c)} className="btn-soft"><Save/></button><button onClick={()=>remove(c.id)} className="rounded-xl bg-red-50 p-3 text-red-600"><Trash2/></button></div></div>)}</div></div></main>}
function IconSelect({value,onChange}:{value:string;onChange:(v:string)=>void}){return <select value={value} onChange={e=>onChange(e.target.value)} className="input text-xl" aria-label="أيقونة القسم">{icons.map(x=><option key={x}>{x}</option>)}</select>}
