"use client";
import { useEffect,useState } from "react";
import { ArrowRight,ImagePlus,Plus,Save,Trash2 } from "lucide-react";
import { compressProductImage } from "@/lib/compress-image";
type Method={id:number;name:string;logoUrl:string|null;active:boolean;sortOrder:number;actionType:string;whatsappMessage:string|null;directUrl:string|null};
const fresh=():Method=>({id:0,name:"",logoUrl:null,active:true,sortOrder:0,actionType:"whatsapp",whatsappMessage:"مرحباً، أريد معرفة تفاصيل طريقة الدفع.",directUrl:null});
export default function PaymentsAdmin(){const [methods,setMethods]=useState<Method[]>([]),[message,setMessage]=useState("");
 async function load(){const a=await fetch('/api/auth/me').then(r=>r.json());if(!a.authenticated){location.href='/admin?next=/admin/payments';return}const x=await fetch('/api/payment-methods').then(r=>r.json());setMethods(x.methods||[])}useEffect(()=>{load()},[]);
 const update=(id:number,key:string,value:any)=>setMethods(xs=>xs.map(x=>x.id===id?{...x,[key]:value}:x));
 async function upload(x:Method,file?:File){if(!file)return;const f=new FormData();f.append('file',await compressProductImage(file));const r=await fetch('/api/upload',{method:'POST',body:f}),img=await r.json();if(r.ok)update(x.id,'logoUrl',img.url);else setMessage(img.error||'تعذر رفع الشعار')}
 async function save(x:Method){const r=await fetch('/api/payment-methods',{method:x.id?'PATCH':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(x)});setMessage(r.ok?'تم حفظ طريقة الدفع':'تعذر الحفظ');await load()}
 async function remove(id:number){if(!confirm('هل تريد حذف طريقة الدفع؟'))return;await fetch(`/api/payment-methods?id=${id}`,{method:'DELETE'});await load()}
 return <main dir="rtl" className="min-h-screen bg-[#fff9fb] p-4 text-[#55434c] md:p-8"><div className="mx-auto max-w-5xl"><div className="flex items-center justify-between"><div><a href="/admin" className="inline-flex items-center gap-2 font-bold"><ArrowRight/> لوحة المدير</a><h1 className="mt-3 text-3xl font-black">طرق الدفع</h1><p>حالياً الأيقونات للاستفسار عبر WhatsApp فقط، ويمكن تحويلها مستقبلاً إلى دفع مباشر.</p></div><button onClick={()=>setMethods(x=>[fresh(),...x])} className="btn-soft"><Plus/> إضافة طريقة</button></div>{message&&<p className="mt-4 rounded-xl bg-white p-3 font-bold">{message}</p>}<div className="mt-6 space-y-4">{methods.map((x,i)=><section key={x.id||`new-${i}`} className="grid items-end gap-4 rounded-3xl bg-white p-5 md:grid-cols-3">
  <div className="flex items-center gap-3">{x.logoUrl?<img src={x.logoUrl} className="h-14 w-24 rounded-xl border object-contain p-1"/>:<span className="grid h-14 w-24 place-items-center rounded-xl border bg-stone-50 text-center text-xs font-black">{x.name||'شعار الدفع'}</span>}<label className="btn-soft cursor-pointer"><ImagePlus/> تغيير الشعار<input type="file" accept="image/*" className="hidden" onChange={e=>upload(x,e.target.files?.[0])}/></label></div>
  <label>اسم الطريقة<input className="input" value={x.name} onChange={e=>update(x.id,'name',e.target.value)}/></label><label>الترتيب<input type="number" className="input" value={x.sortOrder} onChange={e=>update(x.id,'sortOrder',+e.target.value)}/></label>
  <label>وظيفة الضغط<select className="input" value={x.actionType} onChange={e=>update(x.id,'actionType',e.target.value)}><option value="whatsapp">استفسار WhatsApp</option><option value="none">بدون رابط</option><option value="direct">رابط دفع مباشر مستقبلاً</option></select></label>
  {x.actionType==='whatsapp'&&<label className="md:col-span-2">رسالة WhatsApp<input className="input" value={x.whatsappMessage||''} onChange={e=>update(x.id,'whatsappMessage',e.target.value)}/></label>}{x.actionType==='direct'&&<label className="md:col-span-2">رابط الدفع المباشر<input className="input" value={x.directUrl||''} onChange={e=>update(x.id,'directUrl',e.target.value)}/></label>}
  <label className="flex items-center gap-2 font-bold"><input type="checkbox" checked={x.active} onChange={e=>update(x.id,'active',e.target.checked)}/> إظهار في المتجر</label><div className="flex gap-2"><button onClick={()=>save(x)} className="inline-flex items-center gap-2 rounded-xl bg-[#d58fa7] px-5 py-3 font-bold text-white"><Save/> حفظ</button>{x.id>0&&<button onClick={()=>remove(x.id)} className="rounded-xl bg-red-50 px-4 text-red-600"><Trash2/></button>}</div>
 </section>)}</div></div></main>}
