"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {ArrowRight,ImagePlus,Pencil,Trash2} from "lucide-react";
import {compressProductImage} from "@/lib/compress-image";
type Style={imageWidth:string;imageAspect:string;imagePosition:string;titleSize:string;subtitleSize:string;textAlign:string;background:string;buttonBg:string;buttonColor:string;secondButtonBg:string;secondButtonColor:string;buttonRadius:string;animation:string;showStats:boolean;badgeText:string;secondButtonText:string;secondButtonLink:string;stat1Value:string;stat1Label:string;stat2Value:string;stat2Label:string;stat3Value:string;stat3Label:string};
type B={id:number;title:string;subtitle:string|null;imageUrl:string|null;buttonText:string|null;buttonLink:string|null;sortOrder:number;active:boolean;style?:Partial<Style>|null};
const defaultStyle:Style={imageWidth:"46",imageAspect:"portrait",imagePosition:"left",titleSize:"48",subtitleSize:"18",textAlign:"right",background:"#fff8f4",buttonBg:"#a9bb9d",buttonColor:"#ffffff",secondButtonBg:"#fff0ef",secondButtonColor:"#c47f84",buttonRadius:"999",animation:"slide-up",showStats:true,badgeText:"متجر ملابس الأطفال",secondButtonText:"اكتشف الأقسام",secondButtonLink:"#categories",stat1Value:"12-48",stat1Label:"ساعة للتوصيل",stat2Value:"تلقائي",stat2Label:"منتج متنوع",stat3Value:"تلقائي",stat3Label:"توصيل بغداد"};
const blank=()=>({title:"",subtitle:"",imageUrl:"",buttonText:"تسوق الآن",buttonLink:"#products",sortOrder:0,active:true,style:{...defaultStyle}});
export default function Banners(){
 const[ok,setOk]=useState<boolean|null>(null),[items,setItems]=useState<B[]>([]),[draft,setDraft]=useState<any>(blank()),[editing,setEditing]=useState<number|null>(null),[notice,setNotice]=useState(""),[saving,setSaving]=useState(false);
 useEffect(()=>{fetch("/api/auth/me").then(r=>r.json()).then(x=>{setOk(x.authenticated);if(x.authenticated)load()})},[]);
 async function load(){const x=await fetch("/api/banners?admin=1").then(r=>r.json());setItems(x.banners||[])}
 function updateStyle(key:keyof Style,value:string|boolean){setDraft((d:any)=>({...d,style:{...d.style,[key]:value}}))}
 async function upload(original?:File){if(!original)return;setNotice("جاري تجهيز وضغط صورة البنر...");const file=await compressProductImage(original),f=new FormData();f.append("file",file);const r=await fetch("/api/upload",{method:"POST",body:f}),x=await r.json();if(r.ok){setDraft((d:any)=>({...d,imageUrl:x.url}));setNotice("تم تجهيز صورة البنر")}else setNotice(x.error)}
 async function save(e:React.FormEvent){e.preventDefault();setSaving(true);const r=await fetch(editing?`/api/banners/${editing}`:"/api/banners",{method:editing?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(draft)});setSaving(false);setNotice(r.ok?(editing?"تم تحديث البنر":"تمت إضافة البنر"):"تعذر حفظ البنر");if(r.ok){setDraft(blank());setEditing(null);load()}}
 function edit(b:B){setEditing(b.id);setDraft({...b,subtitle:b.subtitle||"",imageUrl:b.imageUrl||"",buttonText:b.buttonText||"",buttonLink:b.buttonLink||"",style:{...defaultStyle,...(b.style||{})}});scrollTo({top:0,behavior:"smooth"})}
 async function remove(id:number){if(!confirm("حذف هذا الإعلان؟"))return;await fetch(`/api/banners/${id}`,{method:"DELETE"});load()}
 async function toggle(b:B){await fetch(`/api/banners/${b.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({...b,active:!b.active})});load()}
 if(ok===null)return <main dir="rtl" className="p-8">جاري التحميل...</main>;if(!ok)return <main dir="rtl" className="p-8">يرجى تسجيل الدخول أولاً.</main>;const s:Style={...defaultStyle,...draft.style};
 return <main dir="rtl" className="min-h-screen bg-[#fff9fb] p-4 md:p-8"><div className="mx-auto max-w-6xl"><Link href="/admin" className="flex gap-2"><ArrowRight/> رجوع للوحة الإدارة</Link><h1 className="mt-5 text-3xl font-black">الإعلانات والبنرات</h1><p>كل بنر يمتلك تنسيقاته وحركته الخاصة.</p>{notice&&<p className="my-4 rounded-xl bg-[#dff0f8] p-3 font-bold">{notice}</p>}
 <form onSubmit={save} className="mt-5 space-y-5 rounded-3xl bg-white p-5"><h2 className="text-xl font-black">{editing?"تعديل البنر":"إضافة بنر جديد"}</h2><div className="grid gap-4 md:grid-cols-2"><label>عنوان الإعلان *<input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} required className="input"/></label><label>النص الثانوي<input value={draft.subtitle} onChange={e=>setDraft({...draft,subtitle:e.target.value})} className="input"/></label><label>نص الزر<input value={draft.buttonText} onChange={e=>setDraft({...draft,buttonText:e.target.value})} className="input"/></label><label>رابط الزر<input value={draft.buttonLink} onChange={e=>setDraft({...draft,buttonLink:e.target.value})} className="input"/></label><label>الترتيب<input value={draft.sortOrder} onChange={e=>setDraft({...draft,sortOrder:+e.target.value})} type="number" className="input"/></label><label className="flex cursor-pointer flex-col items-center justify-center rounded-xl border-2 border-dashed p-4 text-center"><span className="flex gap-2 font-bold"><ImagePlus/> رفع/تغيير الصورة</span><small>{s.imageAspect==="square"?"المربع: 1200 × 1200 بكسل":s.imageAspect==="wide"?"العريض: 1600 × 900 بكسل":"الطولي: 900 × 1200 بكسل"} — قرابة 1MB</small><input type="file" accept="image/*" hidden onChange={e=>upload(e.target.files?.[0])}/></label></div>{draft.imageUrl&&<img src={draft.imageUrl} className="max-h-64 w-full rounded-2xl object-contain"/>}
 <section className="rounded-2xl bg-[#fff9fb] p-4"><h3 className="mb-4 font-black">تنسيق الصورة والنص</h3><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><label>عرض الصورة: {s.imageWidth}%<input type="range" min="30" max="65" value={s.imageWidth} onChange={e=>updateStyle("imageWidth",e.target.value)} className="mt-3 w-full"/></label><Select label="شكل الصورة" value={s.imageAspect} change={v=>updateStyle("imageAspect",v)} options={[["portrait","طولي"],["square","مربع"],["wide","عريض"]]}/><Select label="مكان الصورة" value={s.imagePosition} change={v=>updateStyle("imagePosition",v)} options={[["left","يسار"],["right","يمين"]]}/><Select label="محاذاة الكتابة" value={s.textAlign} change={v=>updateStyle("textAlign",v)} options={[["right","يمين"],["center","وسط"]]}/><label>حجم العنوان: {s.titleSize}px<input type="range" min="24" max="72" value={s.titleSize} onChange={e=>updateStyle("titleSize",e.target.value)} className="mt-3 w-full"/></label><label>حجم الوصف: {s.subtitleSize}px<input type="range" min="12" max="30" value={s.subtitleSize} onChange={e=>updateStyle("subtitleSize",e.target.value)} className="mt-3 w-full"/></label><Color label="خلفية البنر" value={s.background} change={v=>updateStyle("background",v)}/><Select label="حركة المحتوى" value={s.animation} change={v=>updateStyle("animation",v)} options={[["slide-up","صعود ناعم"],["slide-right","من اليمين"],["slide-left","من اليسار"],["fade","ظهور هادئ"]]}/></div></section>
 <section className="rounded-2xl bg-[#fff9fb] p-4"><h3 className="mb-4 font-black">محتوى وألوان الأزرار</h3><div className="mb-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Text label="العبارة الصغيرة أعلى البنر" value={s.badgeText} change={v=>updateStyle("badgeText",v)}/><Text label="نص الزر الثاني" value={s.secondButtonText} change={v=>updateStyle("secondButtonText",v)}/><Text label="رابط الزر الثاني" value={s.secondButtonLink} change={v=>updateStyle("secondButtonLink",v)}/></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Color label="لون الزر الأول" value={s.buttonBg} change={v=>updateStyle("buttonBg",v)}/><Color label="كتابة الزر الأول" value={s.buttonColor} change={v=>updateStyle("buttonColor",v)}/><Color label="لون الزر الثاني" value={s.secondButtonBg} change={v=>updateStyle("secondButtonBg",v)}/><Color label="كتابة الزر الثاني" value={s.secondButtonColor} change={v=>updateStyle("secondButtonColor",v)}/><Select label="شكل الأزرار" value={s.buttonRadius} change={v=>updateStyle("buttonRadius",v)} options={[["999","دائري"],["16","ناعم"],["4","مربع"]]}/></div></section>
 <section className="rounded-2xl bg-[#fff9fb] p-4"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><h3 className="font-black">المربعات الثلاثة أسفل البنر</h3><label className="flex items-center gap-2"><input type="checkbox" checked={s.showStats} onChange={e=>updateStyle("showStats",e.target.checked)}/> إظهار المربعات</label></div><p className="mb-4 text-sm text-gray-600">اكتب أي قيمة تريدها. كلمة «تلقائي» تعرض عدد المنتجات أو سعر توصيل بغداد مباشرة.</p><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><div className="rounded-2xl border bg-white p-3"><b>المربع الأول</b><Text label="الرقم أو القيمة" value={s.stat1Value} change={v=>updateStyle("stat1Value",v)}/><Text label="العبارة" value={s.stat1Label} change={v=>updateStyle("stat1Label",v)}/></div><div className="rounded-2xl border bg-white p-3"><b>المربع الثاني</b><Text label="الرقم أو القيمة" value={s.stat2Value} change={v=>updateStyle("stat2Value",v)}/><Text label="العبارة" value={s.stat2Label} change={v=>updateStyle("stat2Label",v)}/></div><div className="rounded-2xl border bg-white p-3"><b>المربع الثالث</b><Text label="الرقم أو القيمة" value={s.stat3Value} change={v=>updateStyle("stat3Value",v)}/><Text label="العبارة" value={s.stat3Label} change={v=>updateStyle("stat3Label",v)}/></div></div></section>
 <div className="flex flex-wrap gap-3"><button disabled={saving} className="min-w-48 flex-1 rounded-xl bg-[#d58fa7] py-3 font-bold text-white">{saving?"جاري الحفظ...":editing?"حفظ التعديلات":"إضافة البنر"}</button><button type="button" onClick={()=>setDraft((d:any)=>({...d,style:{...defaultStyle}}))} className="rounded-xl border bg-[#fff9fb] px-5 py-3 font-bold">إرجاع التنسيق الافتراضي</button>{editing&&<button type="button" onClick={()=>{setEditing(null);setDraft(blank())}} className="rounded-xl border px-6">إلغاء</button>}</div></form>
 <div className="mt-6 space-y-3">{items.map(b=><div key={b.id} className="flex flex-wrap items-center gap-4 rounded-2xl bg-white p-4">{b.imageUrl?<img src={b.imageUrl} className="size-24 rounded-xl object-cover"/>:<div className="size-24 rounded-xl bg-[#f8dce6]"/>}<div className="min-w-44 flex-1"><b>{b.title}</b><p>{b.subtitle}</p></div><button onClick={()=>edit(b)} className="inline-flex gap-2 rounded-xl bg-[#dff0f8] px-4 py-2"><Pencil/> تعديل كامل</button><button onClick={()=>toggle(b)} className="rounded-xl border px-4 py-2">{b.active?"إخفاء":"إظهار"}</button><button onClick={()=>remove(b.id)} className="rounded-xl bg-red-50 p-3 text-red-600"><Trash2/></button></div>)}</div></div></main>
}
function Select({label,value,change,options}:{label:string;value:string;change:(v:string)=>void;options:string[][]}){return <label>{label}<select value={value} onChange={e=>change(e.target.value)} className="input">{options.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select></label>}
function Color({label,value,change}:{label:string;value:string;change:(v:string)=>void}){return <label>{label}<input type="color" value={value} onChange={e=>change(e.target.value)} className="input h-12"/></label>}
function Text({label,value,change}:{label:string;value:string;change:(v:string)=>void}){return <label className="block">{label}<input value={value} onChange={e=>change(e.target.value)} className="input"/></label>}
